import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'it' | 'en' | 'fr' | 'de' | 'ru' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  it: {
    'hero.title': 'SardiniaRent',
    'hero.subtitle': 'Vivi il mare della Sardegna a bordo di un\'icona senza tempo',
    'hero.boat': 'Riva Bravo 38',
    'hero.description': 'Linee iconiche, comfort assoluto e un\'esperienza su misura per te',
    'hero.cta.availability': 'Richiedi disponibilità',
    'hero.cta.experience': 'Scopri l\'esperienza',
    'nav.language': 'Lingua',
    'it': 'Italiano',
    'en': 'English',
    'fr': 'Français',
    'de': 'Deutsch',
    'ru': 'Русский',
    'es': 'Español',
    'boat.title': 'La Barca',
    'boat.subtitle': 'Il Riva Bravo 38 unisce prestazioni fluide, comfort e un design iconico. Perfetto per chi desidera un\'esperienza esclusiva, elegante e curata in ogni dettaglio.',
    'boat.features.title': 'Caratteristiche principali',
    'boat.gallery.title': 'Galleria',
    'boat.spec.guests': 'Fino a 10 ospiti a bordo',
    'boat.spec.sunpad': 'Ampio prendisole anteriore e posteriore',
    'boat.spec.cabin': 'Cabina interna e bagno',
    'boat.spec.awning': 'Tendalino per le ore più calde',
    'boat.spec.audio': 'Impianto audio di qualità',
    'boat.spec.relax': 'Spazi pensati per il massimo relax',
    'boat.spec.shower': 'Doccetta esterna',
    'features.title': 'Perché scegliere questa esperienza',
    'features.subtitle': 'Scopri la Sardegna dal suo punto di vista migliore: il mare',
    'features.luxury.title': 'A bordo di un\'icona del lusso italiano',
    'features.luxury.description': 'Il Riva Bravo 38 è un simbolo di eleganza senza tempo, riconosciuto in tutto il mondo.',
    'features.skipper.title': 'Skipper professionista',
    'features.skipper.description': 'Conoscenza profonda del territorio e delle calette più esclusive, per un\'esperienza sicura e rilassante.',
    'features.comfort.title': 'Comfort & design',
    'features.comfort.description': 'Ampi spazi prendisole, zone d\'ombra e dettagli curati per vivere il mare con stile.',
    'features.custom.title': 'Esperienza su misura',
    'features.custom.description': 'Ogni uscita è personalizzata in base ai tuoi desideri, ai tempi e alle condizioni del mare.',
    'experience.title': 'Una giornata in mare',
    'experience.description1': 'Un\'esperienza privata pensata per chi vuole vivere il Nord Sardegna in totale comfort e relax. Accompagnati da skipper esperti, navigherete tra calette esclusive e acque cristalline, con tempi personalizzabili in base ai vostri desideri.',
    'experience.description2': 'Tra tuffi e momenti di relax, ogni istante è pensato per farvi vivere il mare al meglio. A bordo potrete godervi il sole, il mare e un aperitivo raffinato, mentre l’orizzonte si tinge d’oro, rendendo la giornata davvero indimenticabile.',
    'experience.cta': 'Richiedi questa esperienza',
    'destinations.title': 'Destinazioni',
    'destinations.subtitle': 'Il meglio della Sardegna, visto dal mare',
    'destinations.maddalena.name': 'Arcipelago della Maddalena',
    'destinations.maddalena.description': 'Isole incontaminate e fondali incredibili',
    'destinations.pools.name': 'Piscine Naturali',
    'destinations.pools.description': 'Acque turchesi e sabbia bianchissima',
    'destinations.spargi.name': 'Isola di Spargi',
    'destinations.spargi.description': 'Natura selvaggia e calette nascoste',
    'destinations.corsica.name': 'Corsica',
    'destinations.corsica.description': 'L\'emozione di una traversata verso le scogliere francesi',
    'destinations.itinerary_note': 'L\'itinerario viene scelto in base alle condizioni meteo e ai tuoi desideri.',
    'inclusions.title': 'Cosa è incluso',
    'inclusions.subtitle': 'Tutto ciò che serve per rilassarti',
    'inclusions.included.title': 'Incluso',
    'inclusions.included.skipper': 'Skipper professionista',
    'inclusions.included.lunch': 'Pranzo a bordo',
    'inclusions.included.welcome': 'Aperitivo di benvenuto',
    'inclusions.included.sup': 'SUP e attrezzatura snorkeling',
    'inclusions.included.insurance': 'Assicurazione completa',
    'inclusions.included.equipment': 'Attrezzatura di bordo',
    'inclusions.extra.title': 'Extra su richiesta',
    'inclusions.extra.catering': 'Catering',
    'inclusions.extra.wine': 'Premium Wine e Champagne',
    'inclusions.extra.hostess': 'Hostess/Barman',
    'inclusions.extra.itineraries': 'Itinerari dedicati',
    'inclusions.extra.events': 'Eventi speciali',
    'pricing.title': 'Prezzi',
    'pricing.subtitle': 'Esperienze su misura',
    'pricing.low_season.title': 'Bassa stagione',
    'pricing.low_season.price': '1000€',
    'pricing.low_season.note': 'Carburante escluso',
    'pricing.high_season.title': 'Alta stagione',
    'pricing.high_season.price': '1300€',
    'pricing.high_season.note': 'Carburante escluso',
    'pricing.sunset.title': 'Tramonto',
    'pricing.sunset.price': '500€',
    'pricing.sunset.note': 'Carburante escluso',
    'pricing.note': 'I prezzi variano in base alla stagione e ai servizi richiesti. Richiedi disponibilità per ricevere una proposta personalizzata, senza impegno.',
    'pricing.cta': 'Richiedi disponibilità',
    'testimonials.title': 'Testimonianze',
    'testimonials.testimonial1.text': 'Un modo unico di scoprire la Sardegna. Barca bellissima e organizzazione impeccabile.',
    'testimonials.testimonial1.author': 'Marco',
    'testimonials.testimonial2.text': 'Esperienza elegante, rilassante e perfetta per una giornata speciale.',
    'testimonials.testimonial2.author': 'Laura',
    'contact.title': 'Pronto a vivere il mare come non l\'hai mai fatto?',
    'contact.subtitle1': 'Regalati un\'esperienza esclusiva a bordo di un Riva.',
    'contact.subtitle2': 'Il mare della Sardegna ti aspetta.',
    'contact.description': 'Compila il modulo indicando la data e il numero di persone. Ti risponderemo rapidamente per organizzare la tua esperienza ideale.',
    'contact.form.name': 'Nome',
    'contact.form.email': 'Email',
    'contact.form.phone': 'Telefono',
    'contact.form.date': 'Data',
    'contact.form.guests': 'Numero di ospiti',
    'contact.form.message': 'Messaggio',
    'contact.form.submit': 'Invia richiesta',
    'contact.form.sending': 'Invio in corso...',
    'contact.form.success': 'Richiesta inviata con successo! Ti contatteremo presto.',
    'contact.form.error': 'Si è verificato un errore. Riprova più tardi.',
    'footer.description': 'Esperienze esclusive in barca nel cuore della Sardegna. Scopri il mare come non l\'hai mai visto.',
    'footer.contacts.title': 'Contatti',
    'footer.hours.title': 'Orari',
    'footer.hours.description': 'Disponibili tutti i giorni durante la stagione estiva. Contattaci per prenotazioni e informazioni.',
    'footer.rights': 'Tutti i diritti riservati.',
  },
  en: {
    'hero.title': 'SardiniaRent',
    'hero.subtitle': 'Experience the Sardinian sea on board a timeless icon',
    'hero.boat': 'Riva Bravo 38',
    'hero.description': 'Iconic lines, absolute comfort and a tailor-made experience for you',
    'hero.cta.availability': 'Check availability',
    'hero.cta.experience': 'Discover the experience',
    'nav.language': 'Language',
    'it': 'Italiano',
    'en': 'English',
    'fr': 'Français',
    'de': 'Deutsch',
    'ru': 'Русский',
    'es': 'Español',
    'boat.title': 'The Boat',
    'boat.subtitle': 'The Riva Bravo 38 combines smooth performance, comfort and an iconic design. Perfect for those who want an exclusive, elegant and detailed experience.',
    'boat.features.title': 'Main features',
    'boat.gallery.title': 'Gallery',
    'boat.spec.guests': 'Up to 10 guests on board',
    'boat.spec.sunpad': 'Large front and rear sunpad',
    'boat.spec.cabin': 'Internal cabin and bathroom',
    'boat.spec.awning': 'Awning for the hottest hours',
    'boat.spec.audio': 'Quality audio system',
    'boat.spec.relax': 'Spaces designed for maximum relaxation',
    'boat.spec.shower': 'External shower',
    'features.title': 'Why choose this experience',
    'features.subtitle': 'Discover Sardinia from its best point of view: the sea',
    'features.luxury.title': 'Aboard an icon of Italian luxury',
    'features.luxury.description': 'The Riva Bravo 38 is a symbol of timeless elegance, recognized worldwide.',
    'features.skipper.title': 'Professional Skipper',
    'features.skipper.description': 'Deep knowledge of the area and the most exclusive coves, for a safe and relaxing experience.',
    'features.comfort.title': 'Comfort & Design',
    'features.comfort.description': 'Large sunpads, shaded areas and refined details to live the sea with style.',
    'features.custom.title': 'Tailor-made experience',
    'features.custom.description': 'Every trip is customized based on your desires, timing and sea conditions.',
    'experience.title': 'A day at sea',
    'experience.description1': 'A private experience designed for those who want to experience North Sardinia in total comfort and relaxation. Accompanied by expert skippers, you will sail among exclusive coves and crystal clear waters, with customizable times based on your desires.',
    'experience.description2': 'Between dives and moments of relaxation, every moment is designed to let you experience the sea at its best. On board you can enjoy the sun, the sea and a refined aperitif, while the horizon turns gold, making the day truly unforgettable.',
    'experience.cta': 'Request this experience',
    'destinations.title': 'Destinations',
    'destinations.subtitle': 'The best of Sardinia, seen from the sea',
    'destinations.maddalena.name': 'Maddalena Archipelago',
    'destinations.maddalena.description': 'Pristine islands and incredible seabed',
    'destinations.pools.name': 'Natural Pools',
    'destinations.pools.description': 'Turquoise waters and white sand',
    'destinations.spargi.name': 'Spargi Island',
    'destinations.spargi.description': 'Wild nature and hidden coves',
    'destinations.corsica.name': 'Corsica',
    'destinations.corsica.description': 'The thrill of a crossing towards the French cliffs',
    'destinations.itinerary_note': 'The itinerary is chosen based on weather conditions and your desires.',
    'inclusions.title': 'What\'s included',
    'inclusions.subtitle': 'Everything you need to relax',
    'inclusions.included.title': 'Included',
    'inclusions.included.skipper': 'Professional skipper',
    'inclusions.included.lunch': 'Lunch on board',
    'inclusions.included.welcome': 'Welcome aperitif',
    'inclusions.included.sup': 'SUP and snorkeling equipment',
    'inclusions.included.insurance': 'Full insurance',
    'inclusions.included.equipment': 'On-board equipment',
    'inclusions.extra.title': 'Extra on request',
    'inclusions.extra.catering': 'Catering',
    'inclusions.extra.wine': 'Premium Wine and Champagne',
    'inclusions.extra.hostess': 'Hostess/Barman',
    'inclusions.extra.itineraries': 'Dedicated itineraries',
    'inclusions.extra.events': 'Special events',
    'pricing.title': 'Prices',
    'pricing.subtitle': 'Tailor-made experiences',
    'pricing.low_season.title': 'Low season',
    'pricing.low_season.price': '1000€',
    'pricing.low_season.note': 'Fuel excluded',
    'pricing.high_season.title': 'High season',
    'pricing.high_season.price': '1300€',
    'pricing.high_season.note': 'Fuel excluded',
    'pricing.sunset.title': 'Sunset',
    'pricing.sunset.price': '500€',
    'pricing.sunset.note': 'Fuel excluded',
    'pricing.note': 'Prices vary based on the season and services requested. Request availability to receive a personalized proposal, without obligation.',
    'pricing.cta': 'Check availability',
    'testimonials.title': 'Testimonials',
    'testimonials.testimonial1.text': 'A unique way to discover Sardinia. Beautiful boat and impeccable organization.',
    'testimonials.testimonial1.author': 'Marco',
    'testimonials.testimonial2.text': 'Elegant, relaxing experience, perfect for a special day.',
    'testimonials.testimonial2.author': 'Laura',
    'contact.title': 'Ready to experience the sea like never before?',
    'contact.subtitle1': 'Treat yourself to an exclusive experience on board a Riva.',
    'contact.subtitle2': 'The Sardinian sea awaits you.',
    'contact.description': 'Fill out the form indicating the date and number of people. We will reply quickly to organize your ideal experience.',
    'contact.form.name': 'Name',
    'contact.form.email': 'Email',
    'contact.form.phone': 'Phone',
    'contact.form.date': 'Date',
    'contact.form.guests': 'Number of guests',
    'contact.form.message': 'Message',
    'contact.form.submit': 'Send request',
    'contact.form.sending': 'Sending...',
    'contact.form.success': 'Request sent successfully! We will contact you soon.',
    'contact.form.error': 'An error occurred. Please try again later.',
    'footer.description': 'Exclusive boat experiences in the heart of Sardinia. Discover the sea like you\'ve never seen it before.',
    'footer.contacts.title': 'Contacts',
    'footer.hours.title': 'Hours',
    'footer.hours.description': 'Available every day during the summer season. Contact us for reservations and information.',
    'footer.rights': 'All rights reserved.',
  },
  fr: {
    'hero.title': 'SardiniaRent',
    'hero.subtitle': 'Vivez la mer de Sardaigne à bord d\'une icône intemporelle',
    'hero.boat': 'Riva Bravo 38',
    'hero.description': 'Lignes iconiques, confort absolu et une expérience sur mesure pour vous',
    'hero.cta.availability': 'Vérifier la disponibilité',
    'hero.cta.experience': 'Découvrez l\'expérience',
    'nav.language': 'Langue',
    'it': 'Italiano',
    'en': 'English',
    'fr': 'Français',
    'de': 'Deutsch',
    'ru': 'Русский',
    'es': 'Español',
    'boat.title': 'Le Bateau',
    'boat.subtitle': 'Le Riva Bravo 38 allie performances fluides, confort et design iconique. Parfait pour ceux qui recherchent une expérience exclusive, élégante et soignée dans les moindres détails.',
    'boat.features.title': 'Caractéristiques principales',
    'boat.gallery.title': 'Galerie',
    'boat.spec.guests': 'Jusqu\'à 10 invités à bord',
    'boat.spec.sunpad': 'Grand bain de soleil avant et arrière',
    'boat.spec.cabin': 'Cabine intérieure et salle de bain',
    'boat.spec.awning': 'Taud de soleil pour les heures les plus chaudes',
    'boat.spec.audio': 'Système audio de qualité',
    'boat.spec.relax': 'Espaces conçus pour une relaxation maximale',
    'boat.spec.shower': 'Douchette extérieure',
    'features.title': 'Pourquoi choisir cette expérience',
    'features.subtitle': 'Découvrez la Sardaigne sous son meilleur angle : la mer',
    'features.luxury.title': 'À bord d\'une icône du luxe italien',
    'features.luxury.description': 'Le Riva Bravo 38 est un symbole d\'élégance intemporelle, reconnu dans le monde entier.',
    'features.skipper.title': 'Skipper professionnel',
    'features.skipper.description': 'Connaissance approfondie du territoire et des criques les plus exclusives, pour une expérience sûre et relaxante.',
    'features.comfort.title': 'Confort & Design',
    'features.comfort.description': 'Grands bains de soleil, zones d\'ombre et détails soignés pour vivre la mer avec style.',
    'features.custom.title': 'Expérience sur mesure',
    'features.custom.description': 'Chaque sortie est personnalisée selon vos désirs, le timing et les conditions de la mer.',
    'experience.title': 'Une journée en mer',
    'experience.description1': 'Une expérience privée conçue pour ceux qui veulent découvrir le nord de la Sardaigne en tout confort et relaxation. Accompagné de skippers experts, vous naviguerez entre criques exclusives et eaux cristallines, avec des horaires personnalisables selon vos envies.',
    'experience.description2': 'Entre plongées et moments de détente, chaque instant est pensé pour vous faire vivre la mer au mieux. À bord, vous pourrez profiter du soleil, de la mer et d\'un apéritif raffiné, tandis que l\'horizon se teinte d\'or, rendant la journée vraiment inoubliable.',
    'experience.cta': 'Demander cette expérience',
    'destinations.title': 'Destinations',
    'destinations.subtitle': 'Le meilleur de la Sardaigne, vu de la mer',
    'destinations.maddalena.name': 'Archipel de la Maddalena',
    'destinations.maddalena.description': 'Îles vierges et fonds marins incroyables',
    'destinations.pools.name': 'Piscines Naturelles',
    'destinations.pools.description': 'Eaux turquoise et sable blanc',
    'destinations.spargi.name': 'Île de Spargi',
    'destinations.spargi.description': 'Nature sauvage et criques cachées',
    'destinations.corsica.name': 'Corse',
    'destinations.corsica.description': 'Le frisson d\'une traversée vers les falaises françaises',
    'destinations.itinerary_note': 'L\'itinéraire est choisi en fonction des conditions météo et de vos envies.',
    'inclusions.title': 'Ce qui est inclus',
    'inclusions.subtitle': 'Tout ce dont vous avez besoin pour vous détendre',
    'inclusions.included.title': 'Inclus',
    'inclusions.included.skipper': 'Skipper professionnel',
    'inclusions.included.lunch': 'Déjeuner à bord',
    'inclusions.included.welcome': 'Apéritif de bienvenue',
    'inclusions.included.sup': 'SUP et équipement de snorkeling',
    'inclusions.included.insurance': 'Assurance complète',
    'inclusions.included.equipment': 'Équipement de bord',
    'inclusions.extra.title': 'Extra sur demande',
    'inclusions.extra.catering': 'Restauration',
    'inclusions.extra.wine': 'Vin Premium et Champagne',
    'inclusions.extra.hostess': 'Hôtesse/Barman',
    'inclusions.extra.itineraries': 'Itinéraires dédiés',
    'inclusions.extra.events': 'Événements spéciaux',
    'pricing.title': 'Prix',
    'pricing.subtitle': 'Expériences sur mesure',
    'pricing.low_season.title': 'Basse saison',
    'pricing.low_season.price': '1000€',
    'pricing.low_season.note': 'Carburant exclu',
    'pricing.high_season.title': 'Haute saison',
    'pricing.high_season.price': '1300€',
    'pricing.high_season.note': 'Carburante escluso',
    'pricing.sunset.title': 'Coucher de soleil',
    'pricing.sunset.price': '500€',
    'pricing.sunset.note': 'Carburant exclu',
    'pricing.note': 'Les prix varient selon la saison et les services demandés. Demandez la disponibilité pour recevoir une proposition personnalisée, sans engagement.',
    'pricing.cta': 'Vérifier la disponibilité',
    'testimonials.title': 'Témoignages',
    'testimonials.testimonial1.text': 'Une façon unique de découvrir la Sardaigne. Magnifique bateau et organisation impeccable.',
    'testimonials.testimonial1.author': 'Marco',
    'testimonials.testimonial2.text': 'Expérience élégante, relaxante et parfaite pour une journée spéciale.',
    'testimonials.testimonial2.author': 'Laura',
    'contact.title': 'Prêt à vivre la mer comme jamais auparavant ?',
    'contact.subtitle1': 'Offrez-vous une expérience exclusive à bord d\'un Riva.',
    'contact.subtitle2': 'La mer de Sardaigne vous attend.',
    'contact.description': 'Remplissez le formulaire en indiquant la date et le nombre de personnes. Nous vous répondrons rapidement pour organiser votre expérience idéale.',
    'contact.form.name': 'Nom',
    'contact.form.email': 'E-mail',
    'contact.form.phone': 'Téléphone',
    'contact.form.date': 'Date',
    'contact.form.guests': 'Nombre de personnes',
    'contact.form.message': 'Message',
    'contact.form.submit': 'Envoyer la demande',
    'contact.form.sending': 'Envoi en cours...',
    'contact.form.success': 'Demande envoyée avec succès ! Nous vous contacterons bientôt.',
    'contact.form.error': 'Une erreur est survenue. Veuillez réessayer plus tard.',
    'footer.description': 'Expériences exclusives en bateau au cœur de la Sardaigne. Découvrez la mer comme vous ne l\'avez jamais vue.',
    'footer.contacts.title': 'Contacts',
    'footer.hours.title': 'Horaires',
    'footer.hours.description': 'Disponible tous les jours pendant la saison estivale. Contactez-nous pour les réservations et informations.',
    'footer.rights': 'Tous droits réservés.',
  },
  de: {
    'hero.title': 'SardiniaRent',
    'hero.subtitle': 'Erleben Sie das sardische Meer an Bord einer zeitlosen Ikone',
    'hero.boat': 'Riva Bravo 38',
    'hero.description': 'Ikonische Linien, absoluter Komfort und ein maßgeschneidertes Erlebnis für Sie',
    'hero.cta.availability': 'Verfügbarkeit prüfen',
    'hero.cta.experience': 'Entdecken Sie das Erlebnis',
    'nav.language': 'Sprache',
    'it': 'Italiano',
    'en': 'English',
    'fr': 'Français',
    'de': 'Deutsch',
    'ru': 'Русский',
    'es': 'Español',
    'boat.title': 'Das Boot',
    'boat.subtitle': 'Die Riva Bravo 38 vereint reibungslose Leistung, Komfort und ein ikonisches Design. Perfekt für diejenigen, die ein exklusives, elegantes und detailreiches Erlebnis suchen.',
    'boat.features.title': 'Hauptmerkmale',
    'boat.gallery.title': 'Galerie',
    'boat.spec.guests': 'Bis zu 10 Gäste an Bord',
    'boat.spec.sunpad': 'Großes Sonnendeck vorne und hinten',
    'boat.spec.cabin': 'Innenkabine und Badezimmer',
    'boat.spec.awning': 'Sonnensegel für die heißesten Stunden',
    'boat.spec.audio': 'Hochwertiges Audiosystem',
    'boat.spec.relax': 'Räume für maximale Entspannung konzipiert',
    'boat.spec.shower': 'Außendusche',
    'features.title': 'Warum diese Erfahrung wählen',
    'features.subtitle': 'Entdecken Sie Sardinien von seiner schönsten Seite: dem Meer',
    'features.luxury.title': 'An Bord einer Ikone des italienischen Luxus',
    'features.luxury.description': 'Die Riva Bravo 38 ist ein Symbol für zeitlose Eleganz, weltweit anerkannt.',
    'features.skipper.title': 'Professioneller Skipper',
    'features.skipper.description': 'Tiefgreifende Kenntnis des Gebiets und der exklusivsten Buchten für ein sicheres und entspanntes Erlebnis.',
    'features.comfort.title': 'Komfort & Design',
    'features.comfort.description': 'Große Sonnendecks, Schattenbereiche und raffinierte Details, um das Meer mit Stil zu erleben.',
    'features.custom.title': 'Maßgeschneidertes Erlebnis',
    'features.custom.description': 'Jede Fahrt wird nach Ihren Wünschen, dem Timing und den Meeresbedingungen angepasst.',
    'experience.title': 'Ein Tag auf See',
    'experience.description1': 'Ein privates Erlebnis für alle, die Nordsardinien in vollem Komfort und Entspannung erleben möchten. Begleitet von erfahrenen Skippern segeln Sie zwischen exklusiven Buchten und kristallklarem Wasser, mit anpassbaren Zeiten nach Ihren Wünschen.',
    'experience.description2': 'Zwischen Tauchgängen und Entspannungsmomenten ist jeder Moment darauf ausgelegt, das Meer in vollen Zügen zu genießen. An Bord können Sie die Sonne, das Meer und einen raffinierten Aperitif genießen, während sich der Horizont gold färbt und den Tag wahrhaft unvergesslich macht.',
    'experience.cta': 'Dieses Erlebnis anfragen',
    'destinations.title': 'Reiseziele',
    'destinations.subtitle': 'Das Beste von Sardinien, vom Meer aus gesehen',
    'destinations.maddalena.name': 'Maddalena-Archipel',
    'destinations.maddalena.description': 'Unberührte Inseln und unglaublicher Meeresboden',
    'destinations.pools.name': 'Natürliche Pools',
    'destinations.pools.description': 'Türkisblaues Wasser und weißer Sand',
    'destinations.spargi.name': 'Insel Spargi',
    'destinations.spargi.description': 'Wilde Natur und versteckte Buchten',
    'destinations.corsica.name': 'Korsika',
    'destinations.corsica.description': 'Der Nervenkitzel einer Überfahrt zu den französischen Klippen',
    'destinations.itinerary_note': 'Die Route wird basierend auf den Wetterbedingungen und Ihren Wünschen gewählt.',
    'inclusions.title': 'Was enthalten ist',
    'inclusions.subtitle': 'Alles, was Sie zum Entspannen brauchen',
    'inclusions.included.title': 'Inklusive',
    'inclusions.included.skipper': 'Professioneller Skipper',
    'inclusions.included.lunch': 'Mittagessen an Bord',
    'inclusions.included.welcome': 'Willkommens-Aperitif',
    'inclusions.included.sup': 'SUP und Schnorchelausrüstung',
    'inclusions.included.insurance': 'Vollkaskoversicherung',
    'inclusions.included.equipment': 'Bordaustattung',
    'inclusions.extra.title': 'Extra auf Anfrage',
    'inclusions.extra.catering': 'Catering',
    'inclusions.extra.wine': 'Premium-Wein und Champagner',
    'inclusions.extra.hostess': 'Hostess/Barman',
    'inclusions.extra.itineraries': 'Spezielle Routen',
    'inclusions.extra.events': 'Besondere Ereignisse',
    'pricing.title': 'Preise',
    'pricing.subtitle': 'Maßgeschneiderte Erlebnisse',
    'pricing.low_season.title': 'Nebensaison',
    'pricing.low_season.price': '1000€',
    'pricing.low_season.note': 'Treibstoff exklusive',
    'pricing.high_season.title': 'Hochsaison',
    'pricing.high_season.price': '1300€',
    'pricing.high_season.note': 'Treibstoff exklusive',
    'pricing.sunset.title': 'Sonnenuntergang',
    'pricing.sunset.price': '500€',
    'pricing.sunset.note': 'Treibstoff exklusive',
    'pricing.note': 'Die Preise variieren je nach Saison und gewünschten Leistungen. Fragen Sie die Verfügbarkeit an, um ein unverbindliches, personalisiertes Angebot zu erhalten.',
    'pricing.cta': 'Verfügbarkeit prüfen',
    'testimonials.title': 'Referenzen',
    'testimonials.testimonial1.text': 'Eine einzigartige Art, Sardinien zu entdecken. Schönes Boot und tadellose Organisation.',
    'testimonials.testimonial1.author': 'Marco',
    'testimonials.testimonial2.text': 'Elegante, entspannte Erfahrung, perfekt für einen besonderen Tag.',
    'testimonials.testimonial2.author': 'Laura',
    'contact.title': 'Bereit, das Meer wie nie zuvor zu erleben?',
    'contact.subtitle1': 'Gönnen Sie sich ein exklusives Erlebnis an Bord einer Riva.',
    'contact.subtitle2': 'Das sardische Meer erwartet Sie.',
    'contact.description': 'Füllen Sie das Formular unter Angabe des Datums und der Personenanzahl aus. Wir werden Ihnen schnell antworten, um Ihr ideales Erlebnis zu organisieren.',
    'contact.form.name': 'Name',
    'contact.form.email': 'E-Mail',
    'contact.form.phone': 'Telefon',
    'contact.form.date': 'Datum',
    'contact.form.guests': 'Anzahl der Gäste',
    'contact.form.message': 'Nachricht',
    'contact.form.submit': 'Anfrage senden',
    'contact.form.sending': 'Wird gesendet...',
    'contact.form.success': 'Anfrage erfolgreich gesendet! Wir werden Sie bald kontaktieren.',
    'contact.form.error': 'Ein Fehler ist aufgetreten. Bitte versuchen Sie es später noch einmal.',
    'footer.description': 'Exklusive Bootserlebnisse im Herzen von Sardinien. Entdecken Sie das Meer, wie Sie es noch nie gesehen haben.',
    'footer.contacts.title': 'Kontakte',
    'footer.hours.title': 'Öffnungszeiten',
    'footer.hours.description': 'Täglich während der Sommersaison verfügbar. Kontaktieren Sie uns für Reservierungen und Informationen.',
    'footer.rights': 'Alle Rechte vorbehalten.',
  },
  ru: {
    'hero.title': 'SardiniaRent',
    'hero.subtitle': 'Ощутите Сардинское море на борту вневременной иконы',
    'hero.boat': 'Riva Bravo 38',
    'hero.description': 'Иконические линии, абсолютный комфорт и индивидуальный подход для вас',
    'hero.cta.availability': 'Проверить наличие',
    'hero.cta.experience': 'Узнать больше',
    'nav.language': 'Язык',
    'it': 'Italiano',
    'en': 'English',
    'fr': 'Français',
    'de': 'Deutsch',
    'ru': 'Русский',
    'es': 'Español',
    'boat.title': 'Лодка',
    'boat.subtitle': 'Riva Bravo 38 сочетает в себе плавность хода, комфорт и культовый дизайн. Идеально подходит для тех, кто хочет эксклюзивного, элегантного и детального опыта.',
    'boat.features.title': 'Основные характеристики',
    'boat.gallery.title': 'Галерея',
    'boat.spec.guests': 'До 10 гостей на борту',
    'boat.spec.sunpad': 'Большой передний и задний шезлонг',
    'boat.spec.cabin': 'Внутренняя каюта и санузел',
    'boat.spec.awning': 'Тент для самых жарких часов',
    'boat.spec.audio': 'Качественная аудиосистема',
    'boat.spec.relax': 'Пространства, предназначенные для максимального расслабления',
    'boat.spec.shower': 'Внешний душ',
    'features.title': 'Почему стоит выбрать этот опыт',
    'features.subtitle': 'Откройте для себя Сардинию с лучшей стороны: с моря',
    'features.luxury.title': 'На борту иконы итальянской роскоши',
    'features.luxury.description': 'Riva Bravo 38 — символ вневременной элегантности, признанный во всем мире.',
    'features.skipper.title': 'Профессиональный шкипер',
    'features.skipper.description': 'Глубокое знание местности и самых эксклюзивных бухт для безопасного и расслабляющего отдыха.',
    'features.comfort.title': 'Комфорт и дизайн',
    'features.comfort.description': 'Большие шезлонги, затененные зоны и изысканные детали для стильного отдыха на море.',
    'features.custom.title': 'Индивидуальный опыт',
    'features.custom.description': 'Каждая поездка настраивается в соответствии с вашими пожеланиями, временем и состоянием моря.',
    'experience.title': 'День в море',
    'experience.description1': 'Частный отдых для тех, кто хочет ощутить Северную Сардинию в полном комфорте и расслаблении. В сопровождении опытных шкиперов вы проплывете среди эксклюзивных бухт и кристально чистых вод, время поездки может быть адаптировано под ваши пожелания.',
    'experience.description2': 'Между погружениями и моментами отдыха каждый миг создан для того, чтобы вы могли насладиться морем в полной мере. На борту вы сможете насладиться солнцем, морем и изысканным аперитивом, пока горизонт окрашивается в золотой цвет, делая день поистине незабываемым.',
    'experience.cta': 'Запросить этот опыт',
    'destinations.title': 'Направления',
    'destinations.subtitle': 'Лучшее на Сардинии, вид с моря',
    'destinations.maddalena.name': 'Архипелаг Ла-Маддалена',
    'destinations.maddalena.description': 'Первозданные острова и невероятное морское дно',
    'destinations.pools.name': 'Природные бассейны',
    'destinations.pools.description': 'Бирюзовая вода и белый песок',
    'destinations.spargi.name': 'Остров Спаржи',
    'destinations.spargi.description': 'Дикая природа и скрытые бухты',
    'destinations.corsica.name': 'Корсика',
    'destinations.corsica.description': 'Трепет от перехода к французским скалам',
    'destinations.itinerary_note': 'Маршрут выбирается исходя из погодных условий и ваших пожеланий.',
    'inclusions.title': 'Что включено',
    'inclusions.subtitle': 'Все, что нужно для отдыха',
    'inclusions.included.title': 'Включено',
    'inclusions.included.skipper': 'Профессиональный шкипер',
    'inclusions.included.lunch': 'Обед на борту',
    'inclusions.included.welcome': 'Приветственный аперитив',
    'inclusions.included.sup': 'SUP и снаряжение для снорклинга',
    'inclusions.included.insurance': 'Полная страховка',
    'inclusions.included.equipment': 'Бортовое оборудование',
    'inclusions.extra.title': 'Дополнительно по запросу',
    'inclusions.extra.catering': 'Кейтеринг',
    'inclusions.extra.wine': 'Вина премиум-класса и шампанское',
    'inclusions.extra.hostess': 'Хостес/Бармен',
    'inclusions.extra.itineraries': 'Специальные маршруты',
    'inclusions.extra.events': 'Особые события',
    'pricing.title': 'Цены',
    'pricing.subtitle': 'Индивидуальные предложения',
    'pricing.low_season.title': 'Низкий сезон',
    'pricing.low_season.price': '1000€',
    'pricing.low_season.note': 'Топливо не включено',
    'pricing.high_season.title': 'Высокий сезон',
    'pricing.high_season.price': '1300€',
    'pricing.high_season.note': 'Топливо не включено',
    'pricing.sunset.title': 'Закат',
    'pricing.sunset.price': '500€',
    'pricing.sunset.note': 'Топливо не включено',
    'pricing.note': 'Цены варьируются в зависимости от сезона и запрашиваемых услуг. Запросите наличие, чтобы получить персональное предложение без обязательств.',
    'pricing.cta': 'Проверить наличие',
    'testimonials.title': 'Отзывы',
    'testimonials.testimonial1.text': 'Уникальный способ открыть для себя Сардинию. Прекрасная лодка и безупречная организация.',
    'testimonials.testimonial1.author': 'Марко',
    'testimonials.testimonial2.text': 'Элегантный, расслабляющий отдых, идеально подходящий для особенного дня.',
    'testimonials.testimonial2.author': 'Лаура',
    'contact.title': 'Готовы ощутить море как никогда раньше?',
    'contact.subtitle1': 'Побалуйте себя эксклюзивным отдыхом на борту Riva.',
    'contact.subtitle2': 'Сардинское море ждет вас.',
    'contact.description': 'Заполните форму, указав дату и количество человек. Мы быстро ответим вам, чтобы организовать ваш идеальный отдых.',
    'contact.form.name': 'Имя',
    'contact.form.email': 'Электронная почта',
    'contact.form.phone': 'Телефон',
    'contact.form.date': 'Дата',
    'contact.form.guests': 'Количество гостей',
    'contact.form.message': 'Сообщение',
    'contact.form.submit': 'Отправить запрос',
    'contact.form.sending': 'Отправка...',
    'contact.form.success': 'Запрос успешно отправлен! Мы свяжемся с вами в ближайшее время.',
    'contact.form.error': 'Произошла ошибка. Пожалуйста, попробуйте позже.',
    'footer.description': 'Эксклюзивные прогулки на лодке в самом сердце Сардинии. Откройте для себя море таким, каким вы его еще не видели.',
    'footer.contacts.title': 'Контакты',
    'footer.hours.title': 'Часы работы',
    'footer.hours.description': 'Доступно каждый день в течение летнего сезона. Свяжитесь с нами для бронирования и информации.',
    'footer.rights': 'Все права защищены.',
  },
  es: {
    'hero.title': 'SardiniaRent',
    'hero.subtitle': 'Vive el mar de Cerdeña a bordo de un icono atemporal',
    'hero.boat': 'Riva Bravo 38',
    'hero.description': 'Líneas icónicas, confort absoluto y una experiencia a medida para ti',
    'hero.cta.availability': 'Consultar disponibilidad',
    'hero.cta.experience': 'Descubre la experiencia',
    'nav.language': 'Idioma',
    'it': 'Italiano',
    'en': 'English',
    'fr': 'Français',
    'de': 'Deutsch',
    'ru': 'Русский',
    'es': 'Español',
    'boat.title': 'El Barco',
    'boat.subtitle': 'El Riva Bravo 38 combina un rendimiento suave, confort y un diseño icónico. Perfecto para quienes desean una experiencia exclusiva, elegante y cuidada en cada detalle.',
    'boat.features.title': 'Características principales',
    'boat.gallery.title': 'Galería',
    'boat.spec.guests': 'Hasta 10 invitados a bordo',
    'boat.spec.sunpad': 'Amplio solárium delantero y trasero',
    'boat.spec.cabin': 'Cabina interna y baño',
    'boat.spec.awning': 'Toldo para las horas más calurosas',
    'boat.spec.audio': 'Sistema de audio de calidad',
    'boat.spec.relax': 'Espacios diseñados para el máximo relax',
    'boat.spec.shower': 'Ducha externa',
    'features.title': 'Por qué elegir esta experiencia',
    'features.subtitle': 'Descubre Cerdeña desde su mejor punto de vista: el mar',
    'features.luxury.title': 'A bordo de un icono del lujo italiano',
    'features.luxury.description': 'El Riva Bravo 38 es un símbolo de elegancia atemporal, reconocido en todo el mundo.',
    'features.skipper.title': 'Skipper profesional',
    'features.skipper.description': 'Conocimiento profundo del territorio y de las calas más exclusivas, para una experiencia segura y relajante.',
    'features.comfort.title': 'Confort y Diseño',
    'features.comfort.description': 'Amplios soláriums, zonas de sombra y detalles cuidados para vivir el mar con estilo.',
    'features.custom.title': 'Experiencia a medida',
    'features.custom.description': 'Cada salida se personaliza según tus deseos, los tiempos y las condiciones del mar.',
    'experience.title': 'Un día en el mar',
    'experience.description1': 'Una experiencia privada pensada para quienes quieren vivir el norte de Cerdeña con total comodidad y relax. Acompañados por skippers expertos, navegaréis entre calas exclusivas y aguas cristalinas, con tiempos personalizables según vuestros deseos.',
    'experience.description2': 'Entre chapuzones y momentos de relax, cada instante está pensado para que vivas el mar al máximo. A bordo podrás disfrutar del sol, del mar y de un aperitivo refinado, mientras el horizonte se tiñe de dorado, haciendo que el día sea inolvidable.',
    'experience.cta': 'Solicita esta experiencia',
    'destinations.title': 'Destinos',
    'destinations.subtitle': 'Lo mejor de Cerdeña, visto desde el mar',
    'destinations.maddalena.name': 'Archipiélago de la Maddalena',
    'destinations.maddalena.description': 'Islas vírgenes y fondos marinos increíbles',
    'destinations.pools.name': 'Piscinas Naturales',
    'destinations.pools.description': 'Aguas turquesas y arena blanca',
    'destinations.spargi.name': 'Isla de Spargi',
    'destinations.spargi.description': 'Naturaleza salvaje y calas escondidas',
    'destinations.corsica.name': 'Córcega',
    'destinations.corsica.description': 'La emoción de una travesía hacia los acantilados franceses',
    'destinations.itinerary_note': 'El itinerario se elige en función de las condiciones meteorológicas y de tus deseos.',
    'inclusions.title': 'Qué está incluido',
    'inclusions.subtitle': 'Todo lo que necesitas para relajarte',
    'inclusions.included.title': 'Incluido',
    'inclusions.included.skipper': 'Skipper profesional',
    'inclusions.included.lunch': 'Almuerzo a bordo',
    'inclusions.included.welcome': 'Aperitivo de bienvenida',
    'inclusions.included.sup': 'SUP y equipo de snorkel',
    'inclusions.included.insurance': 'Seguro completo',
    'inclusions.included.equipment': 'Equipo de a bordo',
    'inclusions.extra.title': 'Extra bajo petición',
    'inclusions.extra.catering': 'Catering',
    'inclusions.extra.wine': 'Vinos Premium y Champagne',
    'inclusions.extra.hostess': 'Azafata/Barman',
    'inclusions.extra.itineraries': 'Itinerarios dedicados',
    'inclusions.extra.events': 'Eventos especiales',
    'pricing.title': 'Precios',
    'pricing.subtitle': 'Experiencias a medida',
    'pricing.low_season.title': 'Temporada baja',
    'pricing.low_season.price': '1000€',
    'pricing.low_season.note': 'Combustible excluido',
    'pricing.high_season.title': 'Temporada alta',
    'pricing.high_season.price': '1300€',
    'pricing.high_season.note': 'Combustible excluido',
    'pricing.sunset.title': 'Atardecer',
    'pricing.sunset.price': '500€',
    'pricing.sunset.note': 'Combustible excluido',
    'pricing.note': 'Los precios varían según la temporada y los servicios solicitados. Solicita disponibilidad para recibir una propuesta personalizada, sin compromiso.',
    'pricing.cta': 'Consultar disponibilidad',
    'testimonials.title': 'Testimonios',
    'testimonials.testimonial1.text': 'Una forma única de descubrir Cerdeña. Barco precioso y organización impecable.',
    'testimonials.testimonial1.author': 'Marco',
    'testimonials.testimonial2.text': 'Experiencia elegante, relajante y perfecta para un día especial.',
    'testimonials.testimonial2.author': 'Laura',
    'contact.title': '¿Listo para vivir el mar como nunca antes?',
    'contact.subtitle1': 'Regálate una experiencia exclusiva a bordo de un Riva.',
    'contact.subtitle2': 'El mar de Cerdeña te espera.',
    'contact.description': 'Rellena el formulario indicando la fecha y el número de personas. Te responderemos rápidamente para organizar tu experiencia ideal.',
    'contact.form.name': 'Nombre',
    'contact.form.email': 'Correo electrónico',
    'contact.form.phone': 'Teléfono',
    'contact.form.date': 'Fecha',
    'contact.form.guests': 'Número de invitados',
    'contact.form.message': 'Mensaje',
    'contact.form.submit': 'Enviar solicitud',
    'contact.form.sending': 'Enviando...',
    'contact.form.success': '¡Solicitud enviada con éxito! Nos pondremos en contacto contigo pronto.',
    'contact.form.error': 'Se ha producido un error. Por favor, inténtalo de nuevo más tarde.',
    'footer.description': 'Experiencias exclusivas en barco en el corazón de Cerdeña. Descubre el mar como nunca lo has visto.',
    'footer.contacts.title': 'Contactos',
    'footer.hours.title': 'Horarios',
    'footer.hours.description': 'Disponible todos los días durante la temporada de verano. Contáctanos para reservas e información.',
    'footer.rights': 'Todos los derechos reservados.',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('it');

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
